### ISSUE TITLE
undefined: sync.Pool

### ISSUE THREAD

**Issue by nooproblem** [go-gomail/gomail#35]
Hi,

When running the command 'go get gopkg.in/gomail.v1' the following error was produced:

gopkg.in/alexcesaro/quotedprintable.v2
../../src/gopkg.in/alexcesaro/quotedprintable.v2/header.go:73: undefined: sync.Pool

https://github.com/alexcesaro/quotedprintable/blob/v2/header.go (line 73).

I am running go 1.4.2 in a Windows environment.

**Comment by alexcesaro** [comment]
What is the output of `go version`?

**Comment by tgulacsi** [comment]
sync.Pool has been introduced in 8c6ef061e3c189e3ac90a451d5680aab9d142618, as of  Wed Dec 18 11:08:34 2013 -0800.
This has became part of go1.4, so it has to work, if you really have go1.4.2.
