### ISSUE TITLE
Error: header.go:76: undefined: sync.Pool

### ISSUE THREAD

**Issue by nebulae1** [go-gomail/gomail#22]
This error seems to be happening on go 1.4.1. It works on go 1.3.3. Is there an incompatibility with go 1.4.1?

**Comment by alexcesaro** [comment]
Are you sure you are using Go 1.4.1? `sync.Pool` exists since Go 1.3 and you should not have this error.
Can you detail how you get this error?

**Comment by nebulae1** [comment]
It works fine on my machine, which is running 1.3.3. My colleague switched
to my branch and downloaded the gomail package, then he got that error. We
double checked the go version, 1.4.1. We are running the same os (Windows)
and IDE(atom).

**Comment by alexcesaro** [comment]
You should first try to do a simple package that uses `sync.Pool` to see if it compiles.

**Comment by nebulae1** [comment]
There was some conflict with app engine. This was fixed when app engine was upgraded to the latest version.
